// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2tsBYpWYzJ1UgeC-KH8TyuAEh4R3Qxoo',
    appId: '1:1075240851189:web:e8a6bc1ca6afbd81d557bc',
    messagingSenderId: '1075240851189',
    projectId: 'jobo-bfa19',
    authDomain: 'jobo-bfa19.firebaseapp.com',
    storageBucket: 'jobo-bfa19.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfDUxiTNFoxdz83HbMhndfNO3KWQnaYSM',
    appId: '1:1075240851189:android:e9316c6e1e3db2b4d557bc',
    messagingSenderId: '1075240851189',
    projectId: 'jobo-bfa19',
    storageBucket: 'jobo-bfa19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAirbX0LQy9OFslLa1jNgILSfrZXmxcAsg',
    appId: '1:1075240851189:ios:207784b2359964e3d557bc',
    messagingSenderId: '1075240851189',
    projectId: 'jobo-bfa19',
    storageBucket: 'jobo-bfa19.firebasestorage.app',
    iosBundleId: 'com.example.jobo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAirbX0LQy9OFslLa1jNgILSfrZXmxcAsg',
    appId: '1:1075240851189:ios:207784b2359964e3d557bc',
    messagingSenderId: '1075240851189',
    projectId: 'jobo-bfa19',
    storageBucket: 'jobo-bfa19.firebasestorage.app',
    iosBundleId: 'com.example.jobo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2tsBYpWYzJ1UgeC-KH8TyuAEh4R3Qxoo',
    appId: '1:1075240851189:web:d8f6c009ad8b120ed557bc',
    messagingSenderId: '1075240851189',
    projectId: 'jobo-bfa19',
    authDomain: 'jobo-bfa19.firebaseapp.com',
    storageBucket: 'jobo-bfa19.firebasestorage.app',
  );
}
